version: "3.9"

services:
  database_ngcash:
    image: postgres
    container_name: database_ngcash
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=ngcash_root
      - POSTGRES_PASSWORD=ngcash
      - POSTGRES_DB=ngcash
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: ngcash
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database_ngcash
    depends_on:
      - database_ngcash

volumes:
  pgdata:
    driver: local